### PR TITLE
Frontend job requirements are React, not Vue

### PR DESCRIPTION
**Pull request by nicklasmoeller**
You should also consider updating [this page](https://github.com/aragon/aragon-wiki/blob/master/docs/dev/index.md#aragon-ui), with more recent informations.

cc @bpierre

### CODE REVIEW

**Comment by sohkai** [comment]
💯 Thanks @nicklasmoeller, not sure how we've missed that one for so long!

> with more recent informations

Was there anything else you found outdated, missing, or wanted to add?

**Comment by nicklasmoeller** [comment]
@sohkai it's mentioning Vue, and the component list you're providing probably needs updating. Haven't looked into what components are exposed, but saw that it's React as well now.

**Comment by nicklasmoeller** [comment]
Linking directly to the `aragon-ui` section of course.

**Comment by Smokyish** [comment]
@nicklasmoeller Thank you for your contribution, merged!

**Comment by sohkai** [comment]
@nicklasmoeller Yeah, that component list is definitely changing as we progress. I think it was meant to be a list of "ideas" as to what we could provide.

**Pull request merged**
