### PR TITLE
Upload Freecoast Festival slides

### PR DESCRIPTION
**Pull request by john-light**
I have the transcript of the presentation as well. Where would be the best place for me to upload that?

### CODE REVIEW

**Comment by john-light** [comment]
@Smokyish I asked a question in the description:

> I have the transcript of the presentation as well. Where would be the best place for me to upload that?

The answer to that question will determine where I decide to actually link this for external visibility.

**Comment by Smokyish** [comment]
@john-light Missed that question.

Is there a video? Since the current wording is "Presentation Videos", would be good to have the presentation video listed in `videos/presentations.md` and the transcript should be converted into MarkDown and added to `documentation/slides/filename.md` with a link to the transcript under the video like the slides are linked, if we there is a video link.

**Comment by Smokyish** [comment]
@john-light Okay, please upload the transcript file as mentioned previously to the slides folder, different types of presentation files need to be considered in the wiki restructuring so will have it saved there until we find a good place for it.

**Comment by john-light** [comment]
@Smokyish uploaded the transcript file

**Pull request merged**
