### PR TITLE
Add list of projects using Aragon

### PR DESCRIPTION
**Pull request by gonzalaga**
Hey guys, added a page to list projects using Aragon for their governance. Also added another page with some real-world companies that are completely decentralized - thought it might be useful. Let me know what you think!

-Dan

### CODE REVIEW

**Comment by izqui** [comment]
Thanks for the contribution, paging @Smokyish in.

@gonzalaga Can you please link it in the mkdocs file? https://github.com/aragon/aragon-wiki/blob/master/mkdocs.yml

**Comment by shyblugs** [comment]
these projects also stated there intention to use Aragon

https://swarm.fund
https://www.spicevc.com

**Comment by Smokyish** [comment]
Thank you for your contribution @gonzalaga!

**Comment by gonzalaga** [comment]
Thanks @Smokyish! I'll make these changes this weekend and recommit.

**Pull request merged**
