### PR TITLE
Translate AragonOS doc to Spanish Fixes #87

### LINKED ISSUE #87: Translate AragonOS doc to Spanish
https://wiki.aragon.one/dev/AragonOS/

### PR DESCRIPTION
**Pull request by alejodosr**
Translation of the AragonOS document based on commits in #95. I have tried to minimise my own biases in the translation.

Thank you for your work, it is a pleasure to contribute to this amazing project!

Cheers,
Alejo Rodríguez 

Fixes #87

### CODE REVIEW

**Comment by Smokyish** [comment]
As the AragonOS document is being updated currently, as you mentioned in the comment, i marked that as a dependancy so there wouldn't be a need to update the translation right away/soon again as #95 is finished.

**Comment by alejodosr** [comment]
Ok, I am working on the merged changes in #95.

**Comment by alejodosr** [comment]
[dd6c8be](https://github.com/aragon/aragon-wiki/pull/98/commits/dd6c8be9a3c1bfd9fceb40ae81896212c2a428c0) implements changes from last merge based on PR #95.

**Comment by Smokyish** [comment]
Thank you @alejodosr!

I will defer the merging upon the review by @izqui who can do the actual Spanish review.

**Comment by andytudhope** [comment]
Hey @alejodosr. Please will you edit the original message above to include the words `Fixes #95` otherwise Status Open Bounty will not pick it up and you will not be rewarded if this gets merged. Please also ensure that you have updated your payment details with an ETH address you own (and not one on an exchange on openbounty.status.im)

**Comment by alejodosr** [comment]
Hey @andytudhope thank you very much for the info. I've changed the title, is it correct? BTW, if you update your payments details in https://openbounty.status.im, it doesn't let you check that the address is properly saved in your profile or similar, does it?

**Comment by andytudhope** [comment]
Yeah, thanks @alejodosr - working well now. Yeah, the site currently doesn't, but there are many improvements on the way (including automated funding at Jorge's request 😉 ). For now, as long as you saw the little green box that tells you your address has been successfully updated, you should be good 👍

**Comment by izqui** [comment]
Muchas gracias @alejodosr!

**Comment by alejodosr** [comment]
Gracias a vosotros @izqui por hacer este gran proyecto! :)

**Pull request merged**
