### PR TITLE
Add Cyber

### PR DESCRIPTION
**Pull request by serejandmyself**
Add Cyber. The projects has 1 active Aragon DAO as of now. But another one is planned according to the WP, which will be in charge of ALL the donated funds

### CODE REVIEW

**Comment by john-light** [comment]
Hi @serejandmyself please click the "CLA" button in the comment above to sign the CLA and then we can merge your PR.

**Comment by serejandmyself** [comment]
@john-light Hey John. I signed it

**Comment by john-light** [comment]
@serejandmyself sorry for the trouble, it doesn't seem to have worked. Could you please double-check/ try again?

**Comment by serejandmyself** [comment]
@john-light Ok, seems to be done this time

**Comment by serejandmyself** [comment]
@john-light hey John, just to double check if its all ok?

**Comment by john-light** [comment]
@serejandmyself lgtm! thanks :smiley:

**Pull request merged**
