### PR TITLE
Create community_content.md file

### PR DESCRIPTION
**Pull request by john-light**

### CODE REVIEW

**Comment by john-light** [comment]
@Smokyish just submitted a PR to add this file to `mkdocs.yml`.

**Comment by Smokyish** [comment]
> @Smokyish just submitted a PR to add this file to mkdocs.yml.

@john-light I don't understand why you wouldn't add it to this PR, is there some specific reason why you would create a new PR instead of doing the requested changes here on this one?

:point_up: 
> Add more commits by pushing to the john-light-patch-5 branch on aragon/aragon-wiki.

**Comment by john-light** [comment]
@Smokyish you asked me to add it to mkdocs so I did. Is there a problem with the way I added it?

**Comment by Smokyish** [comment]
> @Smokyish you asked me to add it to mkdocs so I did. Is there a problem with the way I added it?

@john-light You've created the branch [`john-light-patch-5`](https://github.com/aragon/aragon-wiki/tree/john-light-patch-5) for this PR and a PR compares changes on a given branch to the `master` branch. Thus, if you want to make changes or add stuff to **this** PR, you just make a new commit with changes/additions to that branch and they are automatically reflected here. Now you've created another new branch, [`john-light-patch-6`](https://github.com/aragon/aragon-wiki/tree/john-light-patch-6) and a new PR, which is unnecessary and shouldn't be done since the request was for changes to this PR.

**Comment by john-light** [comment]
@Smokyish but both accomplish the same thing, yes?

**Comment by Smokyish** [comment]
@john-light Basically, but this keeps the repo cleaner as there should be one PR per task/activity/issue/fix where all the changes are recorded so the history and list of PR's doesn't get cluttered with multiple PR's for one small change. It's also a smaller time requirement for the reviewer(s) to check and keep track of the changes in one PR rather than multiple ones for one issue.

**Comment by john-light** [comment]
@Smokyish got it, thank you for explaining! I have made the fix on this branch for your review.

**Pull request merged**
