### PR TITLE
AragonOS grammar and style changes

### PR DESCRIPTION
**Pull request by sohkai**
[f2e09d4](https://github.com/aragon/aragon-wiki/commit/f2e09d4c135046bd496315ec14bb26d6dfaf765c?short_path=4b2b2d8#diff-4b2b2d803d6ba34a3124884c38588dc5) includes the majority of changes.
[41d6aa1](https://github.com/aragon/aragon-wiki/commit/41d6aa11f6f137f5f247c89c19017dfba3450166?short_path=4b2b2d8#diff-4b2b2d803d6ba34a3124884c38588dc5) just includes some reordered sections, to make the changes diff better.

Mostly small changes here and there in the paragraphs. Adds more linking between sections and to the reference implementations whenever possible.

It should be noted that [Oxford commas](https://www.grammarly.com/blog/what-is-the-oxford-comma-and-why-do-people-care-so-much-about-it/) are generally a good idea 😄.

### CODE REVIEW

**Comment by izqui** [comment]
This was so needed, thanks @sohkai!

**Comment by sohkai** [comment]
> There can be multiple instances of an app in an organization

(From https://github.com/aragon/aragon/issues/81#issuecomment-354944070) ahh, I didn't think about this, no wonder some of the text in the upgrading section was about "all apps in a DAO" rather than "all apps in DAOs relying on the same kernel". Might have to revise those parts of the upgrading section again.

And thinking about it, I'm pretty sure the latter isn't possible: each DAO's Kernel has its app code and permissions set stored in its own KernelProxy so no two DAOs would be relying on the same Kernel.

I must be missing something though; isn't there a way for DAOs to delegate the upgrading of their apps to the Aragon Network? Or is that done manually for each DAO by giving the Aragon Network the required roles for their `setAppCode()`?

**Comment by izqui** [comment]
I feel like this needs some clarification that should probably make it to the document. 

`kernel.setAppCode(appId, code)` -> sets the `code` for all app instances of `appId` that rely on the kernel.

An app instance in an organization is:
- An AppProxy contract initialized with a certain kernel address and `appId`.
- When the AppProxy address is present in the Kernel ACL (it has at least one incoming or outgoing permission)

Therefore `kernel.setAppCode` is effectively upgrading all app instances with an appId. The rationale behind this, is that it is better to have many single purpose apps (with different parameters) than just one app that gets parametrized in every use. For example, instead of having one voting app and votes having different characteristics (support, quorum, etc), all votes in a Voting app have the same characteristics.

**Comment by sohkai** [comment]
@Smokyish Thanks! I've made changes in a6c7d4c for you :).

The only sections I modified differently were:

> `permissions that don't exist are automatically failed` would sound better as `permissions that don't exist fail automatically`

Kind of reworded the section, hopefully that's easier to read now.

> `actions requiring yet-to-be-created permissions` to `actions which have not yet been created that require permissions`

Part of the rewording, but wanted to note that the _permissions_ are the ones that need to be created (_actions_ are always defined).

**Comment by Smokyish** [comment]
@sohkai Looks good, were there other changes you wanted to make since you named the PR as WIP?

**Comment by izqui** [comment]
Ready to merge @sohkai!

**Comment by sohkai** [comment]
@Smokyish @izqui I did want to address some of the clarifications made in https://github.com/aragon/aragon-wiki/pull/95#issuecomment-354950056 :).

**Comment by sohkai** [comment]
@izqui @Smokyish Ok, that was less rewording than I thought I was going to have to do. See 
709622f :)

**Comment by izqui** [comment]
Awesome! Ready to merge now :)

**Comment by Smokyish** [comment]
Awesome @sohkai! Merging!

**Pull request merged**
